version: '3.8'

services:
  app:
    build: .
    tty: true
    restart: always
    ports:
      - '3001:3000'
    env_file: ./env/local.env
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
