version: '3.8'

services:
  app:
    build: .
    tty: true
    restart: always
    ports:
      - '3001:3000'
    env_file: ./env/local.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  db:
    image: mysql:8.0.34
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-prootpassword',
        ]
      timeout: 20s
      interval: 5s
      retries: 10

volumes:
  db_data:
